name: Herring Cove
author: Herring Cove
baseurl: /herring-cove
description: theme for jekyll
github: http://www.github.com/arnp
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: rnpatel[at]me.com

theme: jekyll-theme-minimal
